package ar.com.datos.test.compressor.ppmc;

import junit.framework.TestCase;
import ar.com.datos.compressor.ppmc.PPMCSerializer;
import ar.com.datos.documentlibrary.Document;
import ar.com.datos.documentlibrary.MemoryDocument;
import ar.com.datos.test.serializer.mock.OutputBufferTest;

public class TestPPMC extends TestCase{
	
	private MemoryDocument document;
	private OutputBufferTest output;
	private PPMCSerializer serializer;
	
	public TestPPMC(){
		this.serializer = new PPMCSerializer();	
	}
	@Override
	protected void setUp() throws Exception {
		this.output = new OutputBufferTest();
		this.document = new MemoryDocument();
		super.setUp();
	}
	public void doTest(String line){
		this.document.addLine(line);
		this.serializer.dehydrate(this.output, this.document);
		Document hydratedDocument = this.serializer.hydrate(this.output.getAsInputBuffer());
		assertEquals(this.document, hydratedDocument);
	}
	public void test1() {
		doTest("TATAAAAALO");
	}
	public void test2() {
		doTest("QUE QUESO QUEDA QUE");
	}
	public void test3() {
		doTest("LaLaLaLaLaLaLaLaLaLaLaLa");
	}
	public void test4() {
		doTest("koekkoek");
	}
	public void test5() {
		doTest("hola");
	}
	public void test6() {
		doTest("lalalalaaaa");
	}
	public void test7() {
		doTest("asasarassasaras");
	}
	public void test8() {
		doTest("");
	}
	public void test9() {
		doTest("\n");
	}
	public void test10() {
		doTest("a");
	}
	public void test11() {
		doTest("aa");
	}
	public void test12() {
		doTest("aaa");
	}
	public void test13() {
		doTest("ababababa");
	}
	public void test14() {
		doTest("ababab");
	}
	public void test15() {
		doTest("abababc");
	}
	public void test16() {
		doTest("aaaaaaaaaaaaaaaaaaaaaaaaa");
	}
	public void test17() {
		doTest("aaaaaaaaaaaaaa\naaaaaaaaaaas");
	}
	
	public void test18() {
		this.document.addLine("Plan de Estudios ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("   1. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      MATERIA ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("CODIGO ");
		this.document.addLine("");
		this.document.addLine("	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("CREDITOS ");
		this.document.addLine("");
		this.document.addLine("	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("CUATRIMESTRE ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("Organización de Datos ");
		this.document.addLine("");
		this.document.addLine("	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("75.06 ");
		this.document.addLine("");
		this.document.addLine("	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("6 ");
		this.document.addLine("");
		this.document.addLine("	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("6º de Ingeniería en Informática ");
		this.document.addLine("");
		this.document.addLine("5º de Licenciatura en Análisis de Sistemas ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("   1. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      OBJETIVOS ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("Capacitar al alumno en el diseño de soluciones de problemas que requieren grandes volúmenes de datos, utilizando medios de almacenamiento masivos (magnéticos y ópticos), brindándole un base sólida que le permita emplear técnicas y herramientas específicas de programación existentes y crear nuevas de ser necesario. Estar capacitado para operar en forma optima sistemas de organización de información y para mejorar sus rendimientos. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("   1. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      PROGRAMAS ");
		this.document.addLine("");
		this.document.addLine("         1. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("            SINTETICO ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("Sistemas de Archivo en Sistemas Operativos. Organizaciones de Archivos. Catalogación de Textos. Compresión de Archivos. Criptografía. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("   1. ");
		this.document.addLine("");
		this.document.addLine("         1. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("            ANALITICO ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("   1. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Sistemas de Archivo ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Organización lógica de discos y particiones. Directorios y archivos. Asignación de unidades. Seguridad y auditoría de accesos. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Caché de disco (buffering). ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Casos: FAT32 y NTFS (MicroSoft®), Berkeley Software Distribution, EXT 3 (Unix) y HFS (Apple). ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("   1. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Organización de Achivos ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Registros físicos y lógicos; organización de registros de longitud variable; definición lógica y física de registros; accesos secuencial y relativo a registros; caso de estudio; metadatos e independencia lógica de datos. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Concepto de organización de archivo y primitivas; clasificación de archivos y patrones de acceso característicos. Organización secuencial de archivos. Ordenación externa por selección y reemplazo en montículos y por selección natural en montículos. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Árboles B, B+ y B* en archivos. Organizaciones indexadas de archivos. Índices de identificación y de clasificación de registros; índices exhaustivos y selectivos; índices primarios y secundarios. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Organizaciones directas estáticas y dinámicas. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("   1. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Catalogación de Textos ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Estado del arte. Concepto de término y documento. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Índices invertidos: compresión de números de documentos; modelos globales y locales; almacenamiento de términos; construcción de índices invertidos. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Signature files: construcción de signature files; bit slices. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Optimizaciones: case folding; stop words; stemming. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Resolución de consultas: consultas booleanas; wildcards: n-gramas y léxico rotado; consultas ranqueadas; phrase queries: los índices nextword y consultas por proximidad. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("   1. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Compresión de Archivos ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Introducción a la teoría de la Información. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Compresión estadística: Huffman estático y dinámico. Manejo eficiente de Huffman dinámico. Half Coding. Compresión Aritmética. Aritmética de contextos. PPMC. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Compresión no estadística: Run Length. LZ77, LZ78.LZHUFF, LZP. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Localidad en archivos: BS + MTF + SHANNON / Estructurado. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("   1. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Criptografía ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Introducción. Objetivos. Criptografía Clásica. Criptgrafia de clave privada. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Introducción a la criptografía asimétrica. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Criptografia de clave pública. Firmal Digital. Certificados digitales. Pretty Good Privacy (PGP). ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("   1. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Archivos Multimedia ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Introducción. Objetivos. Problemas a resolver característicos de los archivos multimedia. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Buffer en sistemas multimedia. Procesamiento Multimedia en Sistemas de Archivos Ordinarios. Características esperadas de un Sistema de Archivos Multimedia. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Métodos de compresión para datos multimedia (Algoritmos JPEG para imágenes y MPEG para video). ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("   1. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      BIBLIOGRAFIA ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("Tannenbaum, A., Sistemas Operativos Modernos, Segunda Edición, Prentice-Hall. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("Folk M. y Zoellick B., ESTRUCTURAS DE ARCHIVOS: Un Conjunto de Herramientas Conceptuales, Addison-Wesley Iberoamericana, 1992. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("Loomis M., ESTRUCTURA DE DATOS Y ORGANIZACIÓN DE ARCHIVOS, Segunda Edición, Prentice-Hall Hispanoamericana, 1991. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("Silberchatz A., Galvin P., OPERATING SYSTEM CONCEPTS, 5th. Edition, Addison-Wesley. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("Silberschatz A., Korth H., Sudarshan S., DATABASE SYSTEM CONCEPTS, Third Edition, McGraw-Hill, 1998. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("Smith P., Barnes G., FILES & DATABASES AN INTRODUCTION, Addison-Wesley. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("Witten I., Moffat A., Bell T., MANAGING GIGABYTES, Second Edition, Morgan Kaufmann Publishers, 1999. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("   1. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      METODO DE ENSEÑANZA ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("    * ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Clases teórico-prácticas ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("Exposición teórica de conceptos fundamentales, con resolución metódica de problemas tipo y ensayos sobre objetivos. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("    * ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Clases prácticas ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("Resolución por parte de los alumnos y controlada por los docentes auxiliares de problemas correspondientes a las unidades temáticas del programa, ya sea por escrito o por máquina (programas). En general se tratará de problemas abiertos, que generen dudas y motiven la consulta a los docentes y la profundización del conocimiento a través de la bibliografía. Durante el curso se plantearán trabajos prácticos con problemas complejos a resolver por programación, que los alumnos deberán desarrollar en grupo ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("    * ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Clases de consulta ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("Repaso general de temas abordados en clases previas. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("   1. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      MODALIDAD DE LA EVALUACIÓN PARCIAL ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("Evaluación ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("De manejo de conceptos, aplicación de conocimientos y dominio de técnicas, mediante la respuesta a preguntas y la resolución de problemas por escrito en evaluaciones parciales e integradoras, y el desarrollo controlado de trabajos prácticos en computadora. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("Todas las evaluaciones serán parciales, por unidades temáticas, y durante el cursado habrá una oportunidad de evaluación para cada unidad temática. En las fechas de evaluación integradora se debe rendir las unidades que no se hayan aprobado durante el cursado. Cada unidad se puede rendir hasta tres oportunidades. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("La evaluación de los trabajos por computadora es por presentación en tiempo y forma (plazos y formato establecido), método de desarrollo (aplicación de método de desarrollo de programas visto en el curso) y corrección del resultado (cumplimiento de objetivos del programa) ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("   1. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      PROFESOR RESPONSABLE ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      FUNCION ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      DOCENTE ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      e-mail ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Profesor ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Arturo Servetto ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      aserve@gmail.com ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Coordinador de Cátedra ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("   2. ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      CURSOS, TURNOS Y HORARIOS, Y DOCENTES QUE PARTICIPAN ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      CURSO Nº ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      TURNO1 ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      MODALIDAD2 ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      HORARIO ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      AULAS3 ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      CANTIDAD DE ALUMNOS4 ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      CARGO5 ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      DOCENTE6 ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      LEGAJO ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      02 ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Noche ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Teórico-Práctica ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Lunes ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      411 ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      60 ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Profesor Adjunto ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Arturo Servetto ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      123784 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      02 ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Noche ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Teórico-Práctica ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Lunes ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      411 ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      60 ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Ayudante Segundo ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Ariel Piechotka ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      159995 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      02 ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Noche ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Teórico-Práctica ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Miércoles ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      411 ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      60 ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Profesor Adjunto ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Arturo Servetto ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      123784 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      02 ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Noche ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Teórico-Práctica ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Miércoles ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      411 ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      60 ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Ayudante Segundo ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      Alejandro Ferrer ");
		this.document.addLine("");
		this.document.addLine("      	 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("      152965 ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("j).- 2).- ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("TRABAJOS PRACTICOS DE LABORATORIO: Consignar el título y una breve descripción ");
		this.document.addLine("");
		this.document.addLine(" ");
		this.document.addLine("");
		this.document.addLine("Trabajo práctico de programación con dos entregas programadas.");
		
		this.serializer.dehydrate(this.output, this.document);
		Document hydratedDocument = this.serializer.hydrate(this.output.getAsInputBuffer());
		assertEquals(this.document, hydratedDocument);
	}
}
